### ISSUE TITLE
feature suggestion - have an option to round the answers to nearest thousand

### ISSUE THREAD

**Issue by jwm1** [explodecomputer/USSpensions#1]
Suggest to have an option (default?) to round the answers to nearest thousand, for clarity, as the final 3 numbers won't be accurate anyway, and lots of 0s draw the eye, comparisons easier.

**Comment by explodecomputer** [comment]
Thanks for this suggestion also - agree that it would be a bit cleaner but it will be a bit of a pain to code up and really struggling for time. I'll ask around if others are desperate for this and implement if there is demand. The suggestion to add commas was a good one and goes some way towards making more readable
