### ISSUE TITLE
Add current UUK proposal 

### ISSUE THREAD

**Issue by nmdavies** [explodecomputer/USSpensions#9]
This is what UUK are currently consulting on. Would be good to include this as maybe the only option. 

The other proposals were from USS, so are not directly relevant for the UUK consultation. 

<img width="1780" alt="Screenshot 2021-04-30 at 14 16 26" src="https://user-images.githubusercontent.com/8852414/116700414-a7db9c80-a9be-11eb-976e-bd45db98dc42.png">

**Comment by explodecomputer** [comment]
2f9235d
